# Old import
# from config import TRADING_CONFIG, TECHNICAL_PARAMS, FOREX_CONFIG, EXCHANGE_CONFIG

# New import
from ..config.config import (
    TRADING_CONFIG, TECHNICAL_PARAMS, FOREX_CONFIG, EXCHANGE_CONFIG
) 